---
- hosts: new_client
  vars:
    add_client: true
  roles:
    - { role: prepare}
    - { role: chrony, CHRONY_NTP: true}
    - { role: ldap_client, install_client: true}
    - { role: support_ssh_sudo, support: true}