---
# handlers file for ldap_install
- name: restarted ldap client
  systemd:
    name: nslcd
    state: restarted

- name: restarted chrony
  systemd:
    name: chronyd
    state: restarted

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted