---
# 创建的是 OU=Groups 下的其他 ou
- name: 拷贝创建ou文件
  template:
    src: group.ldif.j2
    dest: /tmp/group.ldif

- name: 在 Groups 下创建 OU 组
  shell: ldapadd -x -D "cn=manager,dc={{ SERVER_FQDN.split('.')[1] }},dc={{ SERVER_FQDN.split('.')[2] }}" -w {{ ROOTPW }} -f /tmp/group.ldif
  register: create_result

- debug:
    msg: "{{ create_result.stdout_lines }}"