---
- name: 创建用户
  include: user_add.yml
  tags: create_user

- name: 创建用户组
  include: group_add.yml
  tags: create_group

- name: 为用户增加 sshkey
  include: add_sshkey.yml
  tags: add_sshkey

- name: 将用户添加到组
  include: existing_group.yml
  tags: exist_group

- name: 增加 sudo 规则
  include: sudo_roles.yml
  tags: add_sudoroles