---
- name: crate group
  include: group_add.yml
  when: create_group

- name: create user
  include: user_add.yml
  when: create_user

- name: add user to exist group
  include: existing_group.yml
  when: add_group