---
app_path: /etc/openldap
config_path: /etc/openldap/slapd.d
db_path: /var/lib/ldap

#The self signed ssl parameters
Country: CN
State: Shenzhen
Location: Shenzhen
Organization: IT

# base organization
ORG_USER: Users
ORG_GROUP: Groups
ORG_MANAGERS: Managers