---
- name: general SSHA
  shell: slappasswd -h {SSHA} -s {{ ROOTPW }}
  register: root_password

- name: generate crets ready
  file:
    path: "{{ app_path }}/certs"
    state: directory
    owner: "{{ ldap_user }}"
    group: "{{ ldap_user }}"

- name: generate the private key for certificate request
  shell: openssl genrsa -des3 -passout pass:password -out self1.key 1024
  args:
    chdir: "{{ app_path }}/certs"
    creates: "{{ app_path }}/certs/self1.key"

- name: Strip the passphrase from the key
  shell: openssl rsa -in self1.key -passin pass:password -out self.key
  args:
    chdir: "{{ app_path }}/certs/"
    creates: "{{ app_path }}/certs/self.key"

- name: Create and sign the the new certificate
  shell: openssl req -new -x509 -subj '/C={{ Country }}/ST={{ State }}/L={{ Location }}/O={{ Organization }}/CN={{ SERVER_FQDN }}/' -days 3650 -key self.key -out cert.crt -extensions v3_ca
  args:
    chdir: "{{ app_path }}/certs/"
    creates: "{{ app_path }}/certs/cert.crt"

- name: copy the supporting files stand by TLS
  template:
    src: slap.j2
    dest: /etc/sysconfig/slapd
    mode: 0755