---
- name: setup client support sudo
  blockinfile:
    path: /etc/sudo-ldap.conf
    block: |
      uri ldap://{{ SERVER_FQDN }}
      sudoers_base ou={{ org_sudo }},dc={{ SERVER_FQDN.split('.')[0] }},dc={{ SERVER_FQDN.split('.')[2] }}

- name: setup client support ssh
  blockinfile:
    path: /etc/nsswitch.conf
    block: |
      sudoers:    files   ldap

- name: configuer client ssh client
  yum:
    name: openssh-ldap
    state: latest

- name: copy ldap conf to client
  template:
    src: ldap_ss.conf.j2
    dest: /etc/ssh/ldap.conf

- name: add ssh  config support ssh-key
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      AuthorizedKeysCommand /usr/libexec/openssh/ssh-ldap-wrapper
      AuthorizedKeysCommandUser nobody
      PubkeyAuthentication yes

- name: restart sshd service and nslcd service
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - sshd
    - nslcd